### ISSUE TITLE
Possible type generation issue

### ISSUE THREAD

**Issue by Numpsy** [Zaid-Ajaj/Hawaii#10]
Hi,

An observation from looking at some generated code (I haven't had chance to look at it in any detail, it's just something I spotted).

I have a schema (generated by NSwag from an ASP.Net Core service) which contains this snippet in the components section:

```yaml
"ProblemDetails": {
  "type": "object",
  "additionalProperties": {
    "nullable": true
  },
  "properties": {
    "type": {
      "type": "string",
      "nullable": true
    },
    "title": {
      "type": "string",
      "nullable": true
    },
    "status": {
      "type": "integer",
      "format": "int32",
      "nullable": true
    },
    "detail": {
      "type": "string",
      "nullable": true
    },
    "instance": {
      "type": "string",
      "nullable": true
    },
    "extensions": {
      "type": "object",
      "nullable": true,
      "additionalProperties": {}
    }
  }
},
"ValidationProblemDetails": {
  "allOf": [
    {
      "$ref": "#/components/schemas/ProblemDetails"
    },
    {
      "type": "object",
      "additionalProperties": {
        "nullable": true
      },
      "properties": {
        "errors": {
          "type": "object",
          "nullable": true,
          "additionalProperties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  ]
}
```

(```ProblemDetails``` and ```ValidationProblemDetails``` are classes built into ASP for error reporting fwiw, where the latter is a subclass of the former).

The current Hawaii code generator generates this:

```fsharp
type ProblemDetails = Map<string, Newtonsoft.Json.Linq.JToken>
type ValidationProblemDetails =
    { ``type``: Option<string>
      title: Option<string>
      status: Option<int>
      detail: Option<string>
      instance: Option<string>
      extensions: Option<Map<string, string>>
      errors: Option<Map<string, list<string>>> }
    ///Creates an instance of ValidationProblemDetails with all optional fields initialized to None. The required fields are parameters of this function
    static member Create (): ValidationProblemDetails =
        { ``type`` = None
          title = None
          status = None
          detail = None
          instance = None
          extensions = None
          errors = None }
```

and that bit with the ```Map<string, Newtonsoft.Json.Linq.JToken>``` looks wrong to me - it looks odd how ValidationProblemDetails contains all of the properties from ProblemDetails, but ProblemDetails is defined as a map?

Thanks.
